logging:
  level:
    org.springframework.web: DEBUG
server:
  port: 8088
  servlet:
    context-path: /api/v1

spring:
  application:
    name: controlacceso
  data:
    rest:
      basePath: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/DBMetro
    username: mortega
    password: admin123
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    #hibernate:
      #ddl-auto: update